# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('o', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('c', models.FloatField()),
                ('pair', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OHLC1440',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('o', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('c', models.FloatField()),
                ('pair', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OHLC15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('o', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('c', models.FloatField()),
                ('pair', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OHLC240',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('o', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('c', models.FloatField()),
                ('pair', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OHLC5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('o', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('c', models.FloatField()),
                ('pair', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OHLC60',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('o', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('c', models.FloatField()),
                ('pair', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Spreads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('pair', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='trades',
            name='pair',
            field=models.CharField(default='aa', max_length=10),
            preserve_default=False,
        ),
    ]
