# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20170531_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=10)),
                ('series', models.CharField(max_length=10)),
                ('last', models.CharField(max_length=100)),
            ],
        ),
    ]
